# ──────────────────────────────────────────────
# Kyute CRE Workflow — Project Configuration
# Target: Local Arbitrum One fork (Anvil)
# ──────────────────────────────────────────────

project:
  name: kyute-workflow
  description: "Decentralized funding rate arbitrage vault powered by Chainlink CRE"

# Blockchain RPC endpoints used by local demo
networks:
  arbitrum-one-fork:
    chain_id: 42161
    rpc_url: "http://127.0.0.1:8545"

# Targets
targets:
  local-anvil:
    network: arbitrum-one-fork
    description: "Local simulation against Arbitrum One mainnet fork"

# Workflow definitions
workflows:
  kyute-arb:
    entrypoint: main.ts
    trigger: cron
    schedule: "* * * * *"   # every minute (internal workflow loop runs every 30s)
    description: "Scan rates, execute Boros deposit hedge, and record on-chain audit events"

type: workflow
name: Kyute-Yield-Guardian
version: 1.0.0

triggers:
  - id: cron-trigger
    type: cron
    config:
      schedule: "*/1 * * * *" # Runs every 1 minute natively on CRE

actions:
  - id: run-agent
    type: custom
    ref: ./agent.ts
    trigger: cron-trigger
    inputs:
      rpcUrl: ${RPC_URL}
      privateKey: ${PRIVATE_KEY}
      geminiKey: ${GEMINI_API_KEY}
      vaultAddress: ${STABILITY_VAULT_ADDRESS}
