# ==========================================================================
# CRE PROJECT SETTINGS FILE
# ==========================================================================

staging-settings:
  rpcs:
    - chain-name: ethereum-mainnet-arbitrum-1
      url: https://arb1.arbitrum.io/rpc

production-settings:
  rpcs:
    - chain-name: ethereum-mainnet-arbitrum-1
      url: https://arb1.arbitrum.io/rpc
