# ──────────────────────────────────────────────
# Kyute CRE Workflow — Project Configuration
# Target: Arbitrum Sepolia (simulation)
# ──────────────────────────────────────────────

project:
  name: kyute-workflow
  description: "Decentralized funding rate arbitrage vault powered by Chainlink CRE"

# Blockchain RPC endpoints used during simulation
networks:
  arbitrum-sepolia:
    chain_id: 421614
    rpc_url: "https://arb-sepolia.g.alchemy.com/v2/sjZRV1Sq5ZcLNEI1ZcfEYXz8ob0sBlTx"

# Simulation targets
targets:
  local-simulation:
    network: arbitrum-sepolia
    description: "Local simulation against Arbitrum Sepolia testnet"

# Workflow definitions
workflows:
  kyute-arb:
    entrypoint: main.ts
    trigger: cron
    schedule: "*/5 * * * *"   # every 5 minutes
    description: "Scan CEX/DEX funding rates and execute swaps when spread > 20bps"
