-- ============================================================================
-- kYUte Dashboard Schema (Supabase / Postgres)
-- Purpose:
-- 1) Store Hyperliquid funding rates (mainnet/testnet)
-- 2) Store Boros implied rates
-- 3) Store per-wallet position history points for dashboard graphing
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Realtime publication (idempotent, non-destructive)
-- ----------------------------------------------------------------------------
do $$
begin
  if not exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    create publication supabase_realtime;
  end if;
end $$;

-- ----------------------------------------------------------------------------
-- 1) Hyperliquid funding rates
-- ----------------------------------------------------------------------------
create table if not exists public.hl_funding_rates (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  timestamp timestamptz not null,
  network text not null default 'mainnet',
  asset_symbol text not null,
  venue text not null default 'HlPerp',
  funding_rate numeric not null,      -- raw per-interval funding rate (decimal)
  funding_apr numeric not null,       -- annualized funding rate in %
  next_funding_time timestamptz,
  funding_interval_hours integer,
  constraint hl_funding_rates_network_asset_venue_ts_unique
    unique (network, asset_symbol, venue, timestamp)
);

create index if not exists idx_hl_funding_rates_asset_ts
  on public.hl_funding_rates (asset_symbol, timestamp desc);

alter table public.hl_funding_rates enable row level security;

drop policy if exists "Allow public read access hl_funding_rates" on public.hl_funding_rates;
create policy "Allow public read access hl_funding_rates"
on public.hl_funding_rates for select
to anon
using (true);

drop policy if exists "Allow anon insert hl_funding_rates" on public.hl_funding_rates;
create policy "Allow anon insert hl_funding_rates"
on public.hl_funding_rates for insert
to anon
with check (true);

drop policy if exists "Allow anon update hl_funding_rates" on public.hl_funding_rates;
create policy "Allow anon update hl_funding_rates"
on public.hl_funding_rates for update
to anon
using (true)
with check (true);

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'hl_funding_rates'
  ) then
    alter publication supabase_realtime add table public.hl_funding_rates;
  end if;
end $$;

-- ----------------------------------------------------------------------------
-- 2) Boros implied rates
-- ----------------------------------------------------------------------------
create table if not exists public.boros_implied_rates (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  timestamp timestamptz not null,
  network text not null default 'mainnet',
  market_address text not null,
  asset_symbol text not null default 'ETH',
  implied_apr numeric not null,       -- annualized implied APR in %
  source text not null default 'boros_sdk',
  constraint boros_implied_rates_network_market_ts_unique
    unique (network, market_address, timestamp)
);

create index if not exists idx_boros_implied_rates_asset_ts
  on public.boros_implied_rates (asset_symbol, timestamp desc);

alter table public.boros_implied_rates enable row level security;

drop policy if exists "Allow public read access boros_implied_rates" on public.boros_implied_rates;
create policy "Allow public read access boros_implied_rates"
on public.boros_implied_rates for select
to anon
using (true);

drop policy if exists "Allow anon insert boros_implied_rates" on public.boros_implied_rates;
create policy "Allow anon insert boros_implied_rates"
on public.boros_implied_rates for insert
to anon
with check (true);

drop policy if exists "Allow anon update boros_implied_rates" on public.boros_implied_rates;
create policy "Allow anon update boros_implied_rates"
on public.boros_implied_rates for update
to anon
using (true)
with check (true);

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'boros_implied_rates'
  ) then
    alter publication supabase_realtime add table public.boros_implied_rates;
  end if;
end $$;

-- ----------------------------------------------------------------------------
-- 3) User position history points (for stable dashboard graph)
-- ----------------------------------------------------------------------------
create table if not exists public.hl_position_history (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  timestamp timestamptz not null,
  network text not null default 'testnet',
  wallet_address text not null,
  coin text not null,
  total_open numeric not null,            -- total open amount in base asset (e.g., ETH)
  total_open_usd numeric,                 -- optional denormalized USD notional
  source text not null default 'userFillsByTime',
  constraint hl_position_history_wallet_coin_ts_unique
    unique (wallet_address, coin, timestamp)
);

create index if not exists idx_hl_position_history_wallet_coin_ts
  on public.hl_position_history (wallet_address, coin, timestamp desc);

alter table public.hl_position_history enable row level security;

drop policy if exists "Allow public read access hl_position_history" on public.hl_position_history;
create policy "Allow public read access hl_position_history"
on public.hl_position_history for select
to anon
using (true);

drop policy if exists "Allow anon insert hl_position_history" on public.hl_position_history;
create policy "Allow anon insert hl_position_history"
on public.hl_position_history for insert
to anon
with check (true);

drop policy if exists "Allow anon update hl_position_history" on public.hl_position_history;
create policy "Allow anon update hl_position_history"
on public.hl_position_history for update
to anon
using (true)
with check (true);

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'hl_position_history'
  ) then
    alter publication supabase_realtime add table public.hl_position_history;
  end if;
end $$;

-- ----------------------------------------------------------------------------
-- 4) Canonical kYUte userId <-> wallet mapping
-- ----------------------------------------------------------------------------
create table if not exists public.kyute_user_wallets (
  user_id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  wallet_address text not null unique,
  vault_address text,
  chain_id integer,
  testnet boolean not null default true,
  issued_at timestamptz,
  expires_at timestamptz,
  signature text
);

create index if not exists idx_kyute_user_wallets_vault_updated
  on public.kyute_user_wallets (vault_address, updated_at desc);

alter table public.kyute_user_wallets enable row level security;

drop policy if exists "Allow public read access kyute_user_wallets" on public.kyute_user_wallets;
create policy "Allow public read access kyute_user_wallets"
on public.kyute_user_wallets for select
to anon
using (true);

drop policy if exists "Allow anon insert kyute_user_wallets" on public.kyute_user_wallets;
create policy "Allow anon insert kyute_user_wallets"
on public.kyute_user_wallets for insert
to anon
with check (true);

drop policy if exists "Allow anon update kyute_user_wallets" on public.kyute_user_wallets;
create policy "Allow anon update kyute_user_wallets"
on public.kyute_user_wallets for update
to anon
using (true)
with check (true);

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'kyute_user_wallets'
  ) then
    alter publication supabase_realtime add table public.kyute_user_wallets;
  end if;
end $$;

-- ----------------------------------------------------------------------------
-- 5) Legacy table kept for backwards compatibility with older code paths
-- ----------------------------------------------------------------------------
create table if not exists public.kyute_events (
  id bigint generated by default as identity primary key,
  timestamp timestamptz not null default now(),
  asset_symbol text,
  event_type text not null,
  boros_apr numeric,
  hl_apr numeric,
  spread_bps numeric,
  vault_balance_eth numeric,
  risk_score numeric,
  risk_level text,
  composite_score numeric,
  reason text,
  action text,
  amount_eth numeric,
  market_address text,
  collateral_address text,
  status text
);

alter table public.kyute_events enable row level security;

drop policy if exists "Allow public read access kyute_events" on public.kyute_events;
create policy "Allow public read access kyute_events"
on public.kyute_events for select
to anon
using (true);

drop policy if exists "Allow anon insert kyute_events" on public.kyute_events;
create policy "Allow anon insert kyute_events"
on public.kyute_events for insert
to anon
with check (true);

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'kyute_events'
  ) then
    alter publication supabase_realtime add table public.kyute_events;
  end if;
end $$;
