-- Create the funding_rates table
create table public.funding_rates (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  timestamp timestamptz not null,
  asset_symbol text not null,
  median_apr numeric,
  binance_rate numeric,
  hyperliquid_rate numeric,
  boros_rate numeric default 0,
  spread_bps numeric
);

-- Enable Row Level Security
alter table public.funding_rates enable row level security;

-- Policy: Allow public read access (for Dashboard)
create policy "Allow public read access"
on public.funding_rates for select
to anon
using (true);

-- Policy: Allow anonymous inserts (for Demo/Workflow)
-- CAUTION: In production, use service_role key instead of allowing anon inserts
create policy "Allow anon insert"
on public.funding_rates for insert
to anon
with check (true);

-- Optional: Realtime
begin;
  -- remove the supabase_realtime publication
  drop publication if exists supabase_realtime;
  -- re-create the publication but don't enable it for any tables
  create publication supabase_realtime;
commit;

-- Add table to realtime publication
alter publication supabase_realtime add table public.funding_rates;

-- ------------------------------------------------------------------
-- kyute_events: required for dashboard + Chainlink proof telemetry
-- ------------------------------------------------------------------
create table if not exists public.kyute_events (
  id bigint generated by default as identity primary key,
  timestamp timestamptz not null default now(),
  asset_symbol text,
  event_type text not null,
  boros_apr numeric,
  hl_apr numeric,
  spread_bps numeric,
  vault_balance_eth numeric,
  risk_score numeric,
  risk_level text,
  composite_score numeric,
  reason text,
  action text,
  amount_eth numeric,
  market_address text,
  collateral_address text,
  status text
);

alter table public.kyute_events enable row level security;

drop policy if exists "Allow public read access kyute_events" on public.kyute_events;
create policy "Allow public read access kyute_events"
on public.kyute_events for select
to anon
using (true);

drop policy if exists "Allow anon insert kyute_events" on public.kyute_events;
create policy "Allow anon insert kyute_events"
on public.kyute_events for insert
to anon
with check (true);

alter publication supabase_realtime add table public.kyute_events;
